### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by fquintelagit** [cine-io/cineio-broadcast-android#2]
Few seconds after start a broadcast:

Process: io.cine.example, PID: 5207
    java.lang.OutOfMemoryError
            at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
            at java.nio.MemoryBlock.allocate(MemoryBlock.java:125)
            at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:72)
            at io.cine.android.streaming.FFmpegMuxer.writeSampleData(FFmpegMuxer.java:149)
            at io.cine.android.streaming.AndroidEncoder.drainEncoder(AndroidEncoder.java:128)
            at io.cine.android.streaming.TextureMovieEncoder.handleFrameAvailable(TextureMovieEncoder.java:245)
            at io.cine.android.streaming.TextureMovieEncoder.access$200(TextureMovieEncoder.java:61)
            at io.cine.android.streaming.TextureMovieEncoder$EncoderHandler.handleMessage(TextureMovieEncoder.java:383)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at io.cine.android.streaming.TextureMovieEncoder.run(TextureMovieEncoder.java:215)
            at java.lang.Thread.run(Thread.java:841)

**Comment by sirvon** [comment]
@levantaodedo you get any resolution with this issue, get the same when streaming for a few seconds.
possibly memory leak elsewhere in the code..

**Comment by rokon338** [comment]
yes， i have  the same problem!  OOM

**Comment by oleg-t** [comment]
Having OOM issues here, as well. Very frustrating! However, it happens intermittently. From my experience it seems to be related to stability of the internet connection. 
![screen shot 2015-06-05 at 11 57 02 pm](https://cloud.githubusercontent.com/assets/12043659/8054439/974da114-0e4d-11e5-803f-b1785c59ec63.png)

**Comment by jpxiong** [comment]
I have the same problem on **Android OS 4.4.4** ! 

OOM

```
E/AndroidRuntime(16754): java.lang.OutOfMemoryError
E/AndroidRuntime(16754):    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
E/AndroidRuntime(16754):    at java.nio.MemoryBlock.allocate(MemoryBlock.java:125)
E/AndroidRuntime(16754):    at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:72)
E/AndroidRuntime(16754):    at io.cine.android.streaming.FFmpegMuxer.writeSampleData(FFmpegMuxer.java:149)
E/AndroidRuntime(16754):    at io.cine.android.streaming.AndroidEncoder.drainEncoder(AndroidEncoder.java:128)
E/AndroidRuntime(16754):    at io.cine.android.streaming.TextureMovieEncoder.handleFrameAvailable(TextureMovieEncoder.java:245)
at io.cine.android.streaming.TextureMovieEncoder.access$200(TextureMovieEncoder.java:61)
E/AndroidRuntime(16754):    at io.cine.android.streaming.TextureMovieEncoder$EncoderHandler.handleMessage(TextureMovieEncoder.java:383)
E/AndroidRuntime(16754):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(16754):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(16754):    at io.cine.android.streaming.TextureMovieEncoder.run(TextureMovieEncoder.java:215)
E/AndroidRuntime(16754):    at java.lang.Thread.run(Thread.java:841)
```
