### ISSUE TITLE
Huge memory leak crashing the application.

### ISSUE THREAD

**Issue by cadesalaberry** [cine-io/cineio-broadcast-android#24]
On both the Nexus 4 (4.4.3) and the Samsung S4 (4.4.2) (cf. Screenshots), the broadcast crashes randomly after using too much memory. The SDK is completely unstable, and it is really hard to develop anything durable having the application crash sporadically...

@growlsworth could you have a look at it ?

_The Nexus 4 crashes around 2m46s so I added a second screenshot._

![screenshot from 2015-06-27 17 30 00 cut](https://cloud.githubusercontent.com/assets/1447513/8414558/e6d2684a-1e66-11e5-810c-7c5324373643.png)

![screenshot from 2015-06-29 14 00 14 cut](https://cloud.githubusercontent.com/assets/1447513/8414720/fff9f8f0-1e67-11e5-8a2d-da9d356c4dd6.png)

![screenshot from 2015-06-29 14 02 33 cut](https://cloud.githubusercontent.com/assets/1447513/8414725/0722dbd8-1e68-11e5-9bd0-103e121c10f2.png)

```
java.lang.OutOfMemoryError
    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
    at java.nio.MemoryBlock.allocate(MemoryBlock.java:125)
    at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:72)
    at io.cine.android.streaming.FFmpegMuxer.writeSampleData(FFmpegMuxer.java:151)
    at io.cine.android.streaming.AndroidEncoder.drainEncoder(AndroidEncoder.java:128)
    at io.cine.android.streaming.TextureMovieEncoder.handleFrameAvailable(TextureMovieEncoder.java:264)
    at io.cine.android.streaming.TextureMovieEncoder$EncoderHandler.handleMessage(TextureMovieEncoder.java:409)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at io.cine.android.streaming.TextureMovieEncoder.run(TextureMovieEncoder.java:219)
    at java.lang.Thread.run(Thread.java:841)

```

**Comment by cadesalaberry** [comment]
Related to #2.
